"""
SkillMesh — Learning Models

LearningResource: a single learning item (course, tutorial, project, doc link).
LearningPath: an ordered sequence of resources targeting a specific skill gap.
LearningProgress: a student's enrollment and per-resource completion tracking.
LearningPathEnrollment: links a student to a learning path.

Design rules:
- Learning paths are gap-driven — generated from prioritise_gaps() output.
- Completing a path triggers a reassessment suggestion.
- Gap Closure is computed by comparing before/after StudentSkill proficiency.
- Resources are real URLs to real content — no fake integrations.
- LLMs may later enhance with explanations (Phase 9) but never create scores.
"""

import enum
import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import BaseModel


class ResourceType(str, enum.Enum):
    COURSE = "course"               # Full structured course (e.g. Coursera)
    TUTORIAL = "tutorial"           # Focused tutorial or article
    DOCUMENTATION = "documentation" # Official docs
    PRACTICE_PROJECT = "practice_project"  # Hands-on project
    VIDEO = "video"                 # Video lesson or lecture
    BOOK = "book"                   # Book or textbook chapter
    EXERCISE = "exercise"           # Practice exercises / coding challenges


class ResourceDifficulty(str, enum.Enum):
    BEGINNER = "beginner"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"


class EnrollmentStatus(str, enum.Enum):
    ACTIVE = "active"
    COMPLETED = "completed"
    PAUSED = "paused"
    DROPPED = "dropped"


class ProgressStatus(str, enum.Enum):
    NOT_STARTED = "not_started"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    SKIPPED = "skipped"


# ─── Learning Resource ────────────────────────────────────────────────────────

class LearningResource(BaseModel):
    """
    A single learning item. Curated by SUPER_ADMIN or seeded.
    External resources use real URLs — no fake integrations.
    Internal resources (practice projects) are described with instructions.
    """

    __tablename__ = "learning_resources"

    skill_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("skills.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    competency_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("competencies.id", ondelete="SET NULL"),
        nullable=True,
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    resource_type: Mapped[ResourceType] = mapped_column(
        Enum(ResourceType, name="resource_type", create_type=True),
        nullable=False,
    )
    difficulty: Mapped[ResourceDifficulty] = mapped_column(
        Enum(ResourceDifficulty, name="resource_difficulty", create_type=True),
        nullable=False,
        default=ResourceDifficulty.INTERMEDIATE,
    )
    # External URL (None for internal practice projects)
    url: Mapped[str | None] = mapped_column(String(500), nullable=True)
    # Provider name (e.g. "freeCodeCamp", "official docs", "SkillMesh")
    provider: Mapped[str | None] = mapped_column(String(100), nullable=True)
    # Estimated time to complete in minutes
    estimated_minutes: Mapped[int | None] = mapped_column(Integer, nullable=True)
    is_free: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True, index=True)
    # Expected proficiency gain after completing this resource (0–20 points)
    expected_proficiency_gain: Mapped[float] = mapped_column(
        Float, nullable=False, default=5.0
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    skill: Mapped["Skill"] = relationship("Skill")  # type: ignore[name-defined]

    def __repr__(self) -> str:
        return f"<LearningResource id={self.id} title={self.title!r}>"


# ─── Learning Path ────────────────────────────────────────────────────────────

class LearningPath(BaseModel):
    """
    An ordered sequence of learning resources targeting a specific skill gap.
    Generated by the LearningService based on prioritise_gaps() output.
    One path per skill, tailored to the student's starting proficiency.
    """

    __tablename__ = "learning_paths"

    skill_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("skills.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Target proficiency this path aims to achieve
    target_proficiency: Mapped[float] = mapped_column(Float, nullable=False)
    # Starting proficiency band this path is designed for
    from_proficiency: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    # Total estimated minutes across all resources
    total_estimated_minutes: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    # ── Relationships ──────────────────────────────────────────────────────────
    skill: Mapped["Skill"] = relationship("Skill")  # type: ignore[name-defined]
    path_resources: Mapped[list["LearningPathResource"]] = relationship(
        "LearningPathResource",
        back_populates="path",
        cascade="all, delete-orphan",
        order_by="LearningPathResource.order_index",
    )

    def __repr__(self) -> str:
        return f"<LearningPath id={self.id} skill={self.skill_id} target={self.target_proficiency}>"


class LearningPathResource(BaseModel):
    """
    Join table: LearningPath → LearningResource with ordering.
    """

    __tablename__ = "learning_path_resources"
    __table_args__ = (
        UniqueConstraint("path_id", "resource_id", name="uq_path_resource"),
    )

    path_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("learning_paths.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    resource_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("learning_resources.id", ondelete="CASCADE"),
        nullable=False,
    )
    order_index: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    is_required: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    path: Mapped["LearningPath"] = relationship("LearningPath", back_populates="path_resources")
    resource: Mapped["LearningResource"] = relationship("LearningResource")


# ─── Enrollment ───────────────────────────────────────────────────────────────

class LearningPathEnrollment(BaseModel):
    """
    A student's enrollment in a learning path.
    Tracks overall status and records the proficiency at time of enrollment
    (used later to compute Gap Closure).
    """

    __tablename__ = "learning_path_enrollments"
    __table_args__ = (
        UniqueConstraint("student_id", "path_id", name="uq_student_path"),
    )

    student_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    path_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("learning_paths.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    status: Mapped[EnrollmentStatus] = mapped_column(
        Enum(EnrollmentStatus, name="enrollment_status", create_type=True),
        nullable=False,
        default=EnrollmentStatus.ACTIVE,
        index=True,
    )
    # Proficiency at enrollment time — baseline for Gap Closure
    proficiency_at_enrollment: Mapped[float] = mapped_column(
        Float, nullable=False, default=0.0
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    student: Mapped["User"] = relationship("User")  # type: ignore[name-defined]
    path: Mapped["LearningPath"] = relationship("LearningPath")
    progress_records: Mapped[list["LearningProgress"]] = relationship(
        "LearningProgress",
        back_populates="enrollment",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return (
            f"<LearningPathEnrollment student={self.student_id} "
            f"path={self.path_id} status={self.status}>"
        )


# ─── Progress ─────────────────────────────────────────────────────────────────

class LearningProgress(BaseModel):
    """
    Per-resource completion record within an enrollment.
    Created when a student starts or completes a resource.
    """

    __tablename__ = "learning_progress"
    __table_args__ = (
        UniqueConstraint("enrollment_id", "resource_id", name="uq_enrollment_resource"),
    )

    enrollment_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("learning_path_enrollments.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    resource_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("learning_resources.id", ondelete="CASCADE"),
        nullable=False,
    )
    status: Mapped[ProgressStatus] = mapped_column(
        Enum(ProgressStatus, name="progress_status", create_type=True),
        nullable=False,
        default=ProgressStatus.NOT_STARTED,
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    # Student's self-reported notes or rating for this resource
    notes: Mapped[str | None] = mapped_column(String(500), nullable=True)

    enrollment: Mapped["LearningPathEnrollment"] = relationship(
        "LearningPathEnrollment", back_populates="progress_records"
    )
    resource: Mapped["LearningResource"] = relationship("LearningResource")

    def __repr__(self) -> str:
        return (
            f"<LearningProgress enrollment={self.enrollment_id} "
            f"resource={self.resource_id} status={self.status}>"
        )
